xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2409.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2410.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2411.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2412.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2413.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2414.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2415.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2432.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2433.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2434.root .
hadd btf2016_HVscanMib10_MID700.root btf2016_MiB_10m_*root
rm btf2016_MiB_10m_*root

xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2416.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2417.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2418.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2419.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2420.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2421.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2422.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2423.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2424.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2425.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2435.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_10m_2436.root .
hadd btf2016_HVscanMib10_MID1000.root btf2016_MiB_10m_*root
rm btf2016_MiB_10m_*root

xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2386.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2387.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2388.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2389.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2392.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2393.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2394.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2395.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2396.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2426.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2427.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2428.root .
hadd btf2016_HVscanMib25_MID700.root btf2016_MiB_25m_*root
rm btf2016_MiB_25m_*root

xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2391.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2397.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2398.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2399.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2401.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2402.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2403.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2404.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2405.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2406.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2407.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2408.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2429.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2430.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2431.root .
hadd btf2016_HVscanMib25_MID1000.root btf2016_MiB_25m_*root
rm btf2016_MiB_25m_*root

xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2517.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2518.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2519.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2520.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2521.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2522.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2523.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2524.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2525.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2526.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2527.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2528.root .
xrdcp root://eoscms//eos/cms/store/group/dpg_ecal/comm_ecal/upgrade/testbeam/TimingTB_BTF_Jun2016/ntuples/v4/ntuples_v4/btf2016_MiB_25m_2529.root .
hadd btf2016_HVscanMib25_MID1200.root btf2016_MiB_25m_*root
rm btf2016_MiB_25m_*root
